name: Deploy CDK App to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: antoinedelia/workflows/.github/workflows/cdk.yml@main
    with:
      working-directory: 'infra' 
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
